# Generated by Django 5.0.3 on 2024-06-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_store', '0002_waxpathjson'),
    ]

    operations = [
        migrations.CreateModel(
            name='WAScriptJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('script', models.TextField()),
            ],
            options={
                'db_table': 'WAScriptJson',
            },
        ),
    ]
